name: Build App

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      app-dir: ./

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Build App
        run: npx cross-env NODE_ENV=production PUBLIC_URL=/ SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} yarn build
        working-directory: ${{ env.app-dir }}
        env:
          NEXT_PUBLIC_AUTH_URL: https://fake.auth.tap3d.com
          NEXT_PUBLIC_CDN_URL: https://fake.cdn.tap3d.com
          NEXT_PUBLIC_UNITY_PRODUCT_VERSION: 0.0.1
